# Generated by Django 6.0.3 on 2026-03-16 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(default='ABBR', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompagnieAerienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='AIR AERIAL', max_length=200, null=True)),
                ('abbreviation', models.CharField(default='AA', max_length=5, unique=True)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_entreprise', models.CharField(blank=True, default='COMPANIE_AERIENNE', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(default='ABBR', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DistanceEntreDeuxVilles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FlotteCompanieAerienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='FLOTTE', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='modeleAvion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('fabricant', models.CharField(blank=True, max_length=50, null=True)),
                ('nb_places', models.IntegerField(blank=True, default=200)),
                ('nb_km_max_par_vol', models.IntegerField(blank=True, default=3000)),
                ('nb_km_max_par_exploitation', models.IntegerField(blank=True, default=10000)),
                ('nb_km_maintenance', models.IntegerField(blank=True, default=100)),
                ('nb_heures_maintenance', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5)),
                ('maintenance_fee_percentage', models.IntegerField(blank=True, default=10)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('prenom', models.CharField(blank=True, default='AUCUN', max_length=200, null=True)),
                ('alias', models.CharField(default='AUCUN', max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, default='aucun@fail.com', max_length=200, null=True)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_heures_fonctionnement', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('est_a_maintenir', models.BooleanField(blank=True, default=False)),
                ('est_amorti', models.BooleanField(blank=True, default=False)),
                ('km_parcourus', models.IntegerField(blank=True, default=0)),
                ('indicatif_flotte', models.IntegerField(blank=True, default=1)),
                ('nom_court', models.CharField(blank=True, default='FE', max_length=10, null=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.compagnieaerienne')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.modeleavion')),
            ],
        ),
        migrations.CreateModel(
            name='AvionParFlotte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.avion')),
                ('flotte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.flottecompanieaerienne')),
            ],
        ),
        migrations.CreateModel(
            name='HubCompanieAerienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='HUB', max_length=50, null=True)),
                ('aeroport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.aeroport')),
                ('companie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.compagnieaerienne')),
            ],
        ),
        migrations.AddField(
            model_name='flottecompanieaerienne',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerial.hubcompanieaerienne'),
        ),
        migrations.CreateModel(
            name='LignesParHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.hubcompanieaerienne')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.distanceentredeuxvilles')),
            ],
        ),
        migrations.CreateModel(
            name='AvionParLignes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.avion')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.lignesparhub')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(default='ABBR', max_length=50)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.continent')),
            ],
        ),
        migrations.AddField(
            model_name='compagnieaerienne',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.player'),
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(default='ABBR', max_length=50)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.pays')),
            ],
        ),
        migrations.AddField(
            model_name='distanceentredeuxvilles',
            name='ville1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville1rel', to='aerial.ville'),
        ),
        migrations.AddField(
            model_name='distanceentredeuxvilles',
            name='ville2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville2rel', to='aerial.ville'),
        ),
        migrations.AddField(
            model_name='aeroport',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.ville'),
        ),
    ]
