# Generated by Django 6.0.3 on 2026-03-16 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompagnieAerienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='AIR AERIAL', max_length=200)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_entreprise', models.CharField(blank=True, default='COMPANIE_AERIENNE', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='modeleAvion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('fabricant', models.CharField(blank=True, max_length=50, null=True)),
                ('nb_places', models.IntegerField(blank=True, default=200)),
                ('nb_km_max_par_vol', models.IntegerField(blank=True, default=3000)),
                ('nb_km_max_par_exploitation', models.IntegerField(blank=True, default=10000)),
                ('nb_km_maintenance', models.IntegerField(blank=True, default=100)),
                ('nb_heures_maintenance', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5)),
                ('maintenance_fee_percentage', models.IntegerField(blank=True, default=10)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(blank=True, default='AUCUN', max_length=200)),
                ('alias', models.CharField(blank=True, default='AUCUN', max_length=200)),
                ('email', models.EmailField(blank=True, default='aucun@fail.com', max_length=200)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_heures_fonctionnement', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('est_a_maintenir', models.BooleanField(blank=True, default=False)),
                ('est_amorti', models.BooleanField(blank=True, default=False)),
                ('km_parcourus', models.IntegerField(blank=True, default=0)),
                ('indicatif_flotte', models.IntegerField(blank=True, default=0)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.compagnieaerienne')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.modeleavion')),
            ],
        ),
        migrations.AddField(
            model_name='compagnieaerienne',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.player'),
        ),
    ]
