# Generated by Django 6.0.3 on 2026-03-21 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entreprise', models.CharField(blank=True, choices=[('AER', 'Companie Aerienne'), ('BQ', 'Banque')], default='AER', max_length=5, null=True)),
                ('nom', models.CharField(blank=True, default='AIR AERIAL', max_length=200, null=True)),
                ('abbreviation', models.CharField(default='AA', max_length=5, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('niveau', models.IntegerField(default=1)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistanceEntreDeuxVilles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(default='BOEING', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(default='CG', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('prenom', models.CharField(blank=True, default='NON DEFINI', max_length=200, null=True)),
                ('alias', models.CharField(default='ALIAS', max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, default='aucun@fail.com', max_length=200, null=True)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('entreprise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aerial.entreprise')),
            ],
            bases=('aerial.entreprise',),
        ),
        migrations.CreateModel(
            name='CompagnieAerienne',
            fields=[
                ('entreprise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aerial.entreprise')),
            ],
            bases=('aerial.entreprise',),
        ),
        migrations.CreateModel(
            name='ModeleAvion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('nb_places', models.IntegerField(blank=True, default=200)),
                ('nb_km_max_par_vol', models.IntegerField(blank=True, default=3000)),
                ('nb_km_max_par_exploitation', models.IntegerField(blank=True, default=10000)),
                ('nb_km_avant_maintenance', models.IntegerField(blank=True, default=100)),
                ('nb_heures_par_maintenance', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5)),
                ('maintenance_fee_percentage', models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=5)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=20)),
                ('fabricant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerial.fabricant')),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_a_maintenir', models.BooleanField(blank=True, default=False)),
                ('est_amorti', models.BooleanField(blank=True, default=False)),
                ('km_parcourus', models.IntegerField(blank=True, default=0)),
                ('nom_court', models.CharField(blank=True, default='SILVARILLON', max_length=15, null=True, unique=True)),
                ('statut', models.CharField(blank=True, choices=[('VOL', 'En vol'), ('HANGAR', 'Hangar'), ('MAINTMaintenance', 'Maintenance')], default='HANGAR', max_length=25, null=True)),
                ('modele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerial.modeleavion')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avions', to='aerial.compagnieaerienne')),
            ],
        ),
        migrations.AddField(
            model_name='entreprise',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprises', to='aerial.player'),
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=300, null=True)),
                ('km', models.IntegerField(blank=True, default=1)),
                ('nb_escales', models.IntegerField(blank=True, default=0)),
                ('etapes', models.ManyToManyField(blank=True, to='aerial.distanceentredeuxvilles')),
            ],
        ),
        migrations.CreateModel(
            name='LigneAerienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avions', models.ManyToManyField(to='aerial.avion')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.hub')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.trajet')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(default='NON DEFINI', max_length=15, unique=True)),
                ('peut_etre_hub', models.BooleanField(blank=True, default=False)),
                ('prix_location_hub', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('demande', models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=3, null=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.pays')),
            ],
        ),
        migrations.AddField(
            model_name='trajet',
            name='arrivee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fin_trajet', to='aerial.ville'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debut_trajet', to='aerial.ville'),
        ),
        migrations.AddField(
            model_name='hub',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.ville'),
        ),
        migrations.AddField(
            model_name='distanceentredeuxvilles',
            name='ville1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist_origine', to='aerial.ville'),
        ),
        migrations.AddField(
            model_name='distanceentredeuxvilles',
            name='ville2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dist_destination', to='aerial.ville'),
        ),
        migrations.AddField(
            model_name='hub',
            name='companie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.compagnieaerienne'),
        ),
    ]
