# Generated by Django 6.0.3 on 2026-03-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='cash',
        ),
    ]
