# Generated by Django 6.0.3 on 2026-03-20 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(default='BOEING', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=300, null=True)),
                ('km', models.IntegerField(blank=True, default=1)),
                ('nb_etapes', models.IntegerField(blank=True, default=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='hubcompanieaerienne',
            name='aeroport',
        ),
        migrations.RemoveField(
            model_name='avionparflotte',
            name='avion',
        ),
        migrations.RemoveField(
            model_name='avionparflotte',
            name='flotte',
        ),
        migrations.RemoveField(
            model_name='avionparlignes',
            name='avion',
        ),
        migrations.RemoveField(
            model_name='avionparlignes',
            name='ligne',
        ),
        migrations.RemoveField(
            model_name='pays',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='flottecompanieaerienne',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='hubcompanieaerienne',
            name='companie',
        ),
        migrations.RemoveField(
            model_name='lignesparhub',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='lignesparhub',
            name='trajet',
        ),
        migrations.RenameField(
            model_name='modeleavion',
            old_name='nb_heures_maintenance',
            new_name='nb_heures_par_maintenance',
        ),
        migrations.RenameField(
            model_name='modeleavion',
            old_name='nb_km_maintenance',
            new_name='nb_km_avant_maintenance',
        ),
        migrations.RemoveField(
            model_name='avion',
            name='indicatif_flotte',
        ),
        migrations.RemoveField(
            model_name='avion',
            name='nb_heures_fonctionnement',
        ),
        migrations.AddField(
            model_name='ville',
            name='peut_etre_hub',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='ville',
            name='prix_location_hub',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='avion',
            name='modele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerial.modeleavion'),
        ),
        migrations.AlterField(
            model_name='avion',
            name='nom_court',
            field=models.CharField(blank=True, default='SILVARILLON', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='compagnieaerienne',
            name='type_entreprise',
            field=models.CharField(blank=True, choices=[('AER', 'Companie Aerienne'), ('BQ', 'Banque')], default='AER', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='distanceentredeuxvilles',
            name='ville1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='aerial.ville'),
        ),
        migrations.AlterField(
            model_name='distanceentredeuxvilles',
            name='ville2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivee', to='aerial.ville'),
        ),
        migrations.AlterField(
            model_name='modeleavion',
            name='maintenance_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=3),
        ),
        migrations.AlterField(
            model_name='modeleavion',
            name='prix_achat',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pays',
            name='abbreviation',
            field=models.CharField(default='CG', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='alias',
            field=models.CharField(default='ALIAS', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='prenom',
            field=models.CharField(blank=True, default='NON DEFINI', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='abbreviation',
            field=models.CharField(default='PNR', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeleavion',
            name='fabricant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerial.fabricant'),
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.compagnieaerienne')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.ville')),
            ],
        ),
        migrations.CreateModel(
            name='LigneAerienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avions', models.ManyToManyField(to='aerial.avion')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.hub')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.trajet')),
            ],
        ),
        migrations.DeleteModel(
            name='Aeroport',
        ),
        migrations.DeleteModel(
            name='AvionParFlotte',
        ),
        migrations.DeleteModel(
            name='AvionParLignes',
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='FlotteCompanieAerienne',
        ),
        migrations.DeleteModel(
            name='HubCompanieAerienne',
        ),
        migrations.DeleteModel(
            name='LignesParHub',
        ),
    ]
