# Generated by Django 6.0.3 on 2026-03-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
