# Generated by Django 6.0.3 on 2026-03-16 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0002_continent_alter_avion_indicatif_flotte_pays_ville_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnieaerienne',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerial.aeroport'),
        ),
    ]
