# Generated by Django 6.0.3 on 2026-03-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0002_avion_cash_flow_avion_cash_genere_avion_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='cash_genere',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ligneaerienne',
            name='cash_flow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ligneaerienne',
            name='cash_genere',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
