# Generated by Django 6.0.3 on 2026-03-22 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0002_remove_entreprise_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('cash_flow', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('lvl', models.IntegerField(blank=True, default=1, null=True)),
                ('type_bien_immobilier', models.CharField(blank=True, choices=[('APPART', 'Appartement'), ('VILLA', 'Villa'), ('HOTEL', 'Hôtel'), ('COMMERCE', 'Commerce'), ('BUREAUX', 'Bureaux'), ('ENTREPOT', 'Entrepôt'), ('MANOIR', 'Manoir'), ('CHATEAU', 'Château')], default='VILLA', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.ville')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='biens_immobiliers',
            field=models.ManyToManyField(blank=True, related_name='proprietaires', to='aerial.bienimmobilier'),
        ),
        migrations.CreateModel(
            name='MiniJeuMangue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('lvl', models.IntegerField(blank=True, default=1, null=True)),
                ('cash_flow', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=20, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.player')),
            ],
        ),
    ]
