# Generated by Django 6.0.3 on 2026-03-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0002_fabricant_trajet_remove_hubcompanieaerienne_aeroport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avion',
            name='statut',
            field=models.CharField(blank=True, choices=[('VOL', 'En vol'), ('HANGAR', 'Hangar'), ('MAINTMaintenance', 'Maintenance')], default='HANGAR', max_length=25, null=True),
        ),
    ]
