# Generated by Django 6.0.3 on 2026-03-16 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0002_alter_player_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='alias',
            field=models.CharField(blank=True, default='AUCUN', max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='prenom',
            field=models.CharField(blank=True, default='AUCUN', max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, default='aucun@fail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
