# Generated by Django 6.0.3 on 2026-03-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0003_avion_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='ville',
            name='demande',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=3, null=True),
        ),
    ]
