# Generated by Django 6.0.3 on 2026-03-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0003_bienimmobilier_player_biens_immobiliers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minijeumangue',
            name='image_url',
        ),
    ]
