# Generated by Django 6.0.3 on 2026-03-16 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0003_compagnieaerienne_hub'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceEntreDeuxVilles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField(blank=True, default=1)),
                ('ville1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville1rel', to='aerial.ville')),
                ('ville2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville2rel', to='aerial.ville')),
            ],
        ),
    ]
