# Generated by Django 6.0.3 on 2026-03-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0003_player_alias_player_created_at_player_prenom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='ENTREPRISE', max_length=200)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_entreprise', models.CharField(blank=True, default='CLASSIQUE', max_length=200, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.player')),
            ],
        ),
        migrations.CreateModel(
            name='modeleAvion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('nb_places', models.IntegerField(blank=True, default=200)),
                ('nb_heures_max', models.FloatField(blank=True, default=48)),
                ('nb_heures_maintenance', models.FloatField(blank=True, default=1)),
                ('maintenance_fee_percentage', models.IntegerField(blank=True, default=10)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompagnieAerienne',
            fields=[
                ('entreprise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aerial.entreprise')),
            ],
            bases=('aerial.entreprise',),
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.modeleavion')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.compagnieaerienne')),
            ],
        ),
    ]
