# Generated by Django 6.0.3 on 2026-03-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0004_ville_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='abbreviation',
            field=models.CharField(default='PNR', max_length=10, unique=True),
        ),
    ]
