# Generated by Django 6.0.3 on 2026-03-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0004_emploi_player_emploi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi',
            name='nom',
            field=models.CharField(blank=True, default='CHOMEUR', max_length=200, unique=True),
        ),
    ]
