# Generated by Django 6.0.3 on 2026-03-16 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0004_distanceentredeuxvilles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compagnieaerienne',
            name='hub',
        ),
        migrations.CreateModel(
            name='HubCompanieAerienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='HUB', max_length=50, null=True)),
                ('aeroport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.aeroport')),
                ('companie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.compagnieaerienne')),
            ],
        ),
        migrations.CreateModel(
            name='FlotteCompanieAerienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='FLOTTE', max_length=50, null=True)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.avion')),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aerial.hubcompanieaerienne')),
            ],
        ),
    ]
