# Generated by Django 6.0.3 on 2026-03-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0005_remove_compagnieaerienne_hub_hubcompanieaerienne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LignesParHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='LIGNE', max_length=50, null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.hubcompanieaerienne')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.distanceentredeuxvilles')),
            ],
        ),
    ]
