# Generated by Django 6.0.3 on 2026-03-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0005_alter_ville_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='abbreviation',
            field=models.CharField(default='NON DEFINI', max_length=15, unique=True),
        ),
    ]
