# Generated by Django 6.0.3 on 2026-03-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0006_lignesparhub'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='abbreviation',
            field=models.CharField(default='ABBR', max_length=50),
        ),
        migrations.AddField(
            model_name='pays',
            name='abbreviation',
            field=models.CharField(default='ABBR', max_length=50),
        ),
        migrations.AddField(
            model_name='ville',
            name='abbreviation',
            field=models.CharField(default='ABBR', max_length=50),
        ),
        migrations.AlterField(
            model_name='continent',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pays',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
