# Generated by Django 6.0.3 on 2026-03-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0006_alter_ville_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeleavion',
            name='maintenance_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ville',
            name='prix_location_hub',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
