# Generated by Django 6.0.3 on 2026-03-16 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0007_continent_abbreviation_pays_abbreviation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flottecompanieaerienne',
            name='avion',
        ),
        migrations.CreateModel(
            name='AvionParFlotte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.avion')),
                ('flotte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerial.flottecompanieaerienne')),
            ],
        ),
    ]
