# Generated by Django 6.0.3 on 2026-03-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0007_alter_modeleavion_maintenance_fee_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avion',
            name='nom_court',
            field=models.CharField(blank=True, default='SILVARILLON', max_length=15, null=True, unique=True),
        ),
    ]
