# Generated by Django 6.0.3 on 2026-03-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0008_alter_avion_nom_court'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='nb_etapes',
        ),
        migrations.AddField(
            model_name='trajet',
            name='nb_escales',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
