# Generated by Django 6.0.3 on 2026-03-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0008_remove_flottecompanieaerienne_avion_avionparflotte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avionparflotte',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='lignesparhub',
            name='nom',
        ),
    ]
