# Generated by Django 6.0.3 on 2026-03-21 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0009_remove_trajet_nb_etapes_trajet_nb_escales'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='etapes',
            field=models.ManyToManyField(blank=True, null=True, to='aerial.distanceentredeuxvilles'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='trancon1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trancon1', to='aerial.distanceentredeuxvilles'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='trancon2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trancon2', to='aerial.distanceentredeuxvilles'),
        ),
    ]
