# Generated by Django 6.0.3 on 2026-03-21 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0010_trajet_etapes_trajet_trancon1_trajet_trancon2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='trancon1',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='trancon2',
        ),
        migrations.AddField(
            model_name='trajet',
            name='arrivee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fin', to='aerial.ville'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debut', to='aerial.ville'),
        ),
    ]
