# Generated by Django 6.0.3 on 2026-03-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerial', '0011_remove_trajet_trancon1_remove_trajet_trancon2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='etapes',
            field=models.ManyToManyField(blank=True, to='aerial.distanceentredeuxvilles'),
        ),
    ]
