# Generated by Django 6.0.3 on 2026-03-09 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=200)),
                ('marque', models.CharField(max_length=200)),
                ('modele', models.CharField(max_length=200)),
                ('annee_fabrication', models.IntegerField(default=2025)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_log', models.DateTimeField()),
                ('km', models.IntegerField(default=0)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmax_km.vehicule')),
            ],
        ),
    ]
