# Generated by Django 6.0.3 on 2026-03-16 22:17

import django.db.models.deletion
import django.utils.timezone
import gmax_km.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=200)),
                ('marque', models.CharField(max_length=200)),
                ('modele', models.CharField(blank=True, default='AUCUN', max_length=200)),
                ('annee_fabrication', models.IntegerField(blank=True, default=gmax_km.models.get_current_year, null=True)),
                ('date_acquisition', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_log', models.DateTimeField(default=django.utils.timezone.now)),
                ('km', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmax_km.vehicule')),
            ],
        ),
    ]
