# Generated by Django 6.0.3 on 2026-03-09 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmax_km', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='date_acquisition',
            field=models.DateField(default=datetime.date(2023, 10, 1)),
        ),
    ]
