# Generated by Django 6.0.3 on 2026-03-10 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmax_km', '0002_vehicule_date_acquisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_log',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 10, 8, 34, 35, 411424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='annee_fabrication',
            field=models.IntegerField(blank=True, default=2026, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_acquisition',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 10, 8, 34, 35, 411424, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modele',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
