# Generated by Django 6.0.3 on 2026-03-10 14:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmax_km', '0004_log_created_at_log_updated_at_log_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 10, 14, 35, 7, 814097, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_log',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 10, 14, 35, 7, 814097, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 10, 14, 35, 7, 814097, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_acquisition',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 10, 14, 35, 7, 813097, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
