# Generated by Django 6.0.3 on 2026-03-10 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmax_km', '0005_alter_log_created_at_alter_log_date_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 10, 14, 35, 18, 814779, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_log',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 10, 14, 35, 18, 814779, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 10, 14, 35, 18, 814779, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_acquisition',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 10, 14, 35, 18, 814779, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
