# Generated by Django 6.0.3 on 2026-03-10 14:43

import django.utils.timezone
import gmax_km.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmax_km', '0006_alter_log_created_at_alter_log_date_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_log',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='annee_fabrication',
            field=models.IntegerField(blank=True, default=gmax_km.models.get_current_year, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_acquisition',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
